# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0001_squashed_0006_auto_20171012_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
