# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0003_auto_20160316_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='claims',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='acr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='claims',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='max_age',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='authorization_grant_type',
            field=models.CharField(choices=[('authorization-code', 'Authorization code'), ('implicit', 'Implicit'), ('password', 'Resource owner password-based'), ('client-credentials', 'Client credentials'), ('openid', 'OpenID Connect')], max_length=32),
        ),
    ]
