# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0005_auto_20170514_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='code',
            field=models.CharField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.CharField(max_length=191, unique=True),
        ),
    ]
