# Generated by Django 1.11.1 on 2017-05-14 11:41
import django.db.models.deletion
from django.db import migrations, models

from oauth2_provider.settings import oauth2_settings


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0006_auto_20171214_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='source_refresh_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refreshed_access_token', to=oauth2_settings.REFRESH_TOKEN_MODEL),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='access_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refresh_token', to=oauth2_settings.ACCESS_TOKEN_MODEL),
        ),
    ]
