# Generated by Django 4.1.2 on 2022-10-23 17:51

from django.db import migrations, models
import oauth2_provider.generators
import oauth2_provider.models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0006_alter_application_client_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='client_id',
            field=models.CharField(default=oauth2_provider.generators.generate_client_id, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='client_secret',
            field=oauth2_provider.models.ClientSecretField(blank=True, default=oauth2_provider.generators.generate_client_secret, help_text='Hashed on Save. Copy it now if this is a new secret.', max_length=255),
        ),
        migrations.AlterField(
            model_name='grant',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['client_secret'], name='oauth2_app_client_secret_key'),
        ),
        migrations.AddConstraint(
            model_name='accesstoken',
            constraint=models.UniqueConstraint(fields=('token',), name='oauth2_provider_accesstoken_token_key'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('client_id',), name='oauth2_app_client_id_key'),
        ),
        migrations.AddConstraint(
            model_name='grant',
            constraint=models.UniqueConstraint(fields=('code',), name='oauth2_provider_grant_code_key'),
        ),
    ]
