# Generated by Django 2.1.1 on 2018-10-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0006_auto_20171214_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='code_challenge',
            field=models.CharField(max_length=128, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='code_challenge_method',
            field=models.CharField(max_length=10, blank=True, null=True, choices=[('plain', 'plain'), ('S256', 'S256')]),
        )
    ]
