# Generated by Django 5.0.7 on 2024-08-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0010_application_allowed_origins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='hash_client_secret',
            field=models.BooleanField(default=True, help_text='Uncheck if you need to support OIDC with JWT and HS256.'),
        ),
    ]
