# Generated by Django A.B.C on YYYY-MM-DD HH:MM
from django.db import migrations, models
from oauth2_provider.settings import oauth2_settings


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0012_add_token_checksum'),
        migrations.swappable_dependency(oauth2_settings.REFRESH_TOKEN_MODEL)
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.TextField(),
        ),
    ]