# Generated by Django 5.1.4 on 2025-01-06 15:49

import oauth2_provider.generators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0012_add_token_checksum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='authorization_grant_type',
            field=models.CharField(choices=[('authorization-code', 'Authorization code'), ('urn:ietf:params:oauth:grant-type:device_code', 'Device Code'), ('implicit', 'Implicit'), ('password', 'Resource owner password-based'), ('client-credentials', 'Client credentials'), ('openid-hybrid', 'OpenID connect hybrid')], max_length=64),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_code', models.CharField(max_length=100, unique=True)),
                ('user_code', models.CharField(max_length=100)),
                ('scope', models.CharField(default='openid', max_length=64)),
                ('interval', models.IntegerField(default=5)),
                ('expires', models.DateTimeField()),
                ('status', models.CharField(blank=True, choices=[('authorized', 'Authorized'), ('authorization-pending', 'Authorization pending'), ('expired', 'Expired'), ('denied', 'Denied')], default='authorization-pending', max_length=64)),
                ('client_id', models.CharField(db_index=True, default=oauth2_provider.generators.generate_client_id, max_length=100)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
                'swappable': 'OAUTH2_PROVIDER_DEVICE_MODEL',
                'constraints': [models.UniqueConstraint(fields=('device_code',), name='unique_device_code')],
            },
        ),
    ]
