# Generated by Django 5.2 on 2025-06-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0012_add_token_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='backchannel_logout_uri',
            field=models.URLField(blank=True, help_text='Backchannel Logout URI where logout tokens will be sent', null=True),
        ),
    ]
