# Generated by Django 5.2 on 2025-05-05 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from oauth2_provider.settings import oauth2_settings


class Migration(migrations.Migration):
    dependencies = [
        ("oauth2_provider", "0012_add_token_checksum"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="backchannel_logout_session_required",
            field=models.BooleanField(default=False, help_text="Include SID claim in logout token?"),
        ),
        migrations.AddField(
            model_name="application",
            name="backchannel_logout_uri",
            field=models.URLField(
                blank=True, help_text="Backchannel Logout URI where logout tokens will be sent", null=True
            ),
        ),
        migrations.CreateModel(
            name="LogoutToken",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=oauth2_settings.APPLICATION_MODEL
                    ),
                ),
                (
                    "id_token",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=oauth2_settings.ID_TOKEN_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "OAUTH2_PROVIDER_LOGOUT_TOKEN_MODEL",
            },
        ),
    ]
