# Generated by Django 4.1.5 on 2023-01-14 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_ID_TOKEN_MODEL),
        ("tests", "0002_swapped_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="basetestapplication",
            name="post_logout_redirect_uris",
            field=models.TextField(blank=True, help_text="Allowed Post Logout URIs list, space separated"),
        ),
        migrations.AddField(
            model_name="sampleapplication",
            name="post_logout_redirect_uris",
            field=models.TextField(blank=True, help_text="Allowed Post Logout URIs list, space separated"),
        ),
    ]
